export const JWT_CONSTANS = {
  ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
  REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,
  ACCESS_SESSION_EXPIRES_IN: process.env.ACCESS_SESSION_EXPIRES_IN,
};
